steps:
    # build the container images
    - name: 'gcr.io/cloud-builders/docker'
      id: Build Image
      args: ["build", "-t", "gcr.io/$PROJECT_ID/cloud-run", "."]
#       ['build', '-t', 'gcr.io/$PROJECT_ID/cra-cloud-run' ]
      
    # push the container images to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      id: Push Imange
      args: ["push", "gcr.io/$PROJECT_ID/cloud-run"]
#       ['push', 'gcr.io/$PROJECT_ID/cra-cloud-run']
      
    # Deploy container images to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      id: Deploy to Cloud Run
      args:
        [
          'run',
          'deploy',
          'cloud-run',
          '--image',
          'gcr.io/$PROJECT_ID/cloud-run',
          '--region',
          'us-central1',
          '--platform',
          'managed',
          '--quiet',
          '--allow-unauthenticated',
        ]
images:
  - gcr.io/$PROJECT_ID/cloud-run
