steps:
   # frontend deployment
   # Step 1: For installing dependencies
    - name: "gcr.io/cloud-builders/npm"
      id: Install
      args: ["install"]


   # Step 2: For creating optinimized build
    - name: "gcr.io/cloud-builders/npm"
      id: Build
      args: ["run", "build"]
      
    # Deploy container images to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
        [
          'run',
          'deploy',
          'cloud-run',
          '--image',
          'gcr.io/$PROJECT_ID/cloud-run',
          '--region',
          'us-central1',
          '--platform',
          'managed',
          '--quiet',
          '--allow-unauthenticated',
        ]
images:
  - gcr.io/$PROJECT_ID/cloud-run
