steps:
    # build the container images
    - name: 'gcr.io/cloud-builders/docker'
      args: ["build", "-t", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}", "."]
#       ['build', '-t', 'gcr.io/$PROJECT_ID/cra-cloud-run' ]
      
    # push the container images to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}"]
#       ['push', 'gcr.io/$PROJECT_ID/cra-cloud-run']
      
    # Deploy container images to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
        [
          'run',
          'deploy',
          'react-ci-cd',
          '--image',
          'gcr.io/$PROJECT_ID/react-ci-cd',
          '--region',
          'us-central1',
          '--platform',
          'managed',
          '--quiet',
          '--allow-unauthenticated',
        ]
images:
  - gcr.io/$PROJECT_ID/react-ci-cd
